/* ==========================================================================
   rux-ds — BUILDER                                    roadmap §4.12, creator 3
   --------------------------------------------------------------------------
   The page builder's behaviour, for builder.html (generated by
   tools/build-builder.mjs). Hand-written, and deliberately NOT in js/:
   tools/new-project.sh copies js/*.js into every consumer's vendor/, and
   tools/lib/stats.mjs counts js/ as the published module set. This file
   belongs to one page in this repository.

   WHAT IT DOES, this stage: fetches builder/blocks.json, offers the ten
   templates and the answers new-project.sh asks, and keeps ONE PAGE MODEL
   PER TEMPLATE (builder/page.mjs) — the template's own blocks to begin with,
   then whatever the reader adds from the catalogue, moves or removes. The
   model is composed into the page by composePage, which puts every instance
   through instanceOf so a block placed twice keeps its labels bound to its
   own radios, and the preview shows the result in an iframe at a chosen
   width. Every block on the page is offered by label, its editable text is
   listed, and an edit is written back through applyTextEdits, keyed by the
   INSTANCE (`id@n`) so two copies edit apart. Every one of those actions can
   be UNDONE, and the whole session survives a reload as a draft.

   ONE HISTORY, AND ONE ENTRY PER ACTION. builder/session.mjs holds the
   history and the draft; this file decides what an action IS. Every user
   action goes through change() or typed(), which snapshot before, run the
   whole action — Remove touches both the edits and the model, and that is
   ONE entry, not two — and record only if something actually moved. The
   low-level setters below (setEdit, dropEdits, setPage) never touch history
   themselves, which is what keeps an action atomic. Navigation records
   nothing: switching template, slot, block, catalogue or width is not a
   change, so undo and redo instead SELECT the template the action happened
   on, and say so in the button's name.

   THE PREVIEW IS A BLOB URL, not srcdoc. A srcdoc document inherits the
   parent's base URL, so `href="#main-content"` — every template's skip link
   — can resolve to builder.html#main-content and navigate the frame away. A
   blob: document created here has this origin and a URL of its own, so
   fragments stay put and css/, js/ and assets/ load by absolute URL. The
   URL is revoked once the frame has loaded it.

   NOTHING HERE CONSTRUCTS rux-- MARKUP. The chrome is in the generated page,
   where check-classes reads it; this file only fills <select>s, toggles
   aria-pressed and disabled, writes an iframe's src and size, and CLONES the
   four <template>s builder.html ships — a text field, the no-fields line,
   and the two notices. Real component markup is authored in the generator
   and cloned here, never assembled out of class-name strings.

   AND IT CAN BE TAKEN AWAY. Two delivery paths, no third: download the page
   for a project that exists, or copy the whole <main> to replace one; or, for
   a project that does not exist yet, copy the exact new-project.sh command
   built from the answers. THE SCRIPT STAYS THE ONE PROJECT CREATOR — the
   builder writes a page, never a project — and tools/check-parity.mjs holds
   exportPage to the script's own page-writing lines, run per template.

   NOT YET: the guided mode, and escaping the answers as HTML — neither this
   nor the script does, and both say so rather than pretending otherwise.
   ========================================================================== */
import { compose, previewPage, exportPage, bodyOnly, textFieldsOf, linksOf, applyTextEdits, integrity } from './rewrites.mjs';
import { newPage, add, move, remove, unitOf, entriesOf, composePage } from './page.mjs';
import { emptyHistory, pushed, undone, redone, runKey, sameRun,
         toDraft, fromDraft, agoOf, copy, identical } from './session.mjs';

const ROOT = new URL('.', location.href).href;
const DRAFT_KEY = 'rux.draft';
const SAVE_MS = 500;
const $ = s => document.querySelector(s);
const frame = $('#bld-frame'), wrap = $('#bld-frame-wrap'), status = $('#bld-status'), integrityLine = $('#bld-integrity');

// `pages` holds one model per template, made on first use from the manifest
// and kept when the reader switches away and back. `edits` is namespaced per
// template, then per ENTRY KEY (`id@n`, so two instances edit apart), then by
// FIELD INDEX into that block's original html: { template: { key: { 0: 'text' } } }.
// It is pruned as it goes — typing a value back to the original deletes the
// index, an empty map is deleted outright, and removing a block drops its
// edits — so the count in the status line and Reset's disabled state cannot
// drift from it.
//
// THE SNAPSHOT IS `pages`, `edits` AND THE FIVE ANSWERS, and nothing else.
// `template`, `block`, `slot`, `catalogue` and `width` are where the reader
// is standing and what they are looking through, not what they have made.
const ANSWERS = ['theme', 'prefix', 'name', 'title', 'page'];
const FRESH = { theme: 'white', prefix: '', name: '', title: '', page: '' };
const state = { template: 'app-shell', block: '', slot: '', catalogue: '', width: 'fit', ...FRESH, edits: {}, links: {}, pages: {} };
let manifest = null;
let history = emptyHistory();
let run = null;                  // the typing run in progress, or null
let saveTimer = null, saveBlocked = false, unopened = false;
const templates = new Map();     // name → source text
const blocks = new Map();        // id → manifest block

const answers = () => {
  const prefix = state.prefix.trim() || 'Rux';
  const name = state.name.trim() || 'DS';
  return { theme: state.theme, prefix, name, title: state.title.trim() || `${prefix} ${name}` };
};

async function fetchText(url) {
  const r = await fetch(url, { cache: 'no-store' });
  if (!r.ok) throw new Error(`${url}: ${r.status}`);
  return r.text();
}

async function source(name) {
  if (!templates.has(name)) templates.set(name, await fetchText(`templates/${name}.html`));
  return templates.get(name);
}

const templateOf = name => manifest.templates.find(x => x.name === name);
// The template's own blocks by name, for the round trip on its own slots.
const blocksOf = t => Object.fromEntries(manifest.blocks.filter(b => b.source === t.path).map(b => [b.name, b]));
const pageOf = () => (state.pages[state.template] ??= newPage(manifest, state.template));
const setPage = p => { state.pages[state.template] = p; };
const entries = () => entriesOf(pageOf(), templateOf(state.template));
const entryOf = key => entries().find(e => e.key === key);
// The saved edits for one entry, or an empty map. Never creates the maps.
const editsFor = (tpl, key) => (state.edits[tpl] ?? {})[key] ?? {};
// The same, for link targets. TWO STORES, ONE SHAPE, and deliberately not one
// map with mixed keys: a text edit indexes textFieldsOf and a link edit
// indexes linksOf, so sharing an index space would make either one shift the
// other — and a draft written before links existed would silently retarget.
const linksFor = (tpl, key) => (state.links[tpl] ?? {})[key] ?? {};
// A block is native when it is the template's own, at instance 1.
const isNative = (e, t) => e.n === 1 && blocks.get(e.id).source === t.path;
const short = cls => (cls ?? '').split(/\s+/).filter(Boolean).map(c => c.replace(/^rux--/, '')).join(' ');
const labelOf = key => blocks.get(entryOf(key)?.id)?.label ?? 'block';

// ── HISTORY ────────────────────────────────────────────────────────────────

// A COPY, ALWAYS. Handing back live references made change() compare an
// object with itself — fn() mutates state.pages in place, so `before` moved
// with it, every action looked like a no-op and the first browser run
// recorded an empty history after add, edit and remove. Copying here makes
// that mistake unavailable to every caller rather than fixing it at one.
const snapshot = () => copy({
  pages: state.pages,
  edits: state.edits,
  links: state.links,
  answers: Object.fromEntries(ANSWERS.map(k => [k, state[k]])),
});

// Put a restored snapshot back, controls included. The five answers are DOM
// state as well as data, so they are written back here rather than left for
// a render to notice.
function applySnapshot(s) {
  state.pages = copy(s.pages);
  state.edits = copy(s.edits);
  // `?? {}` because a draft written before stage 8 has no links at all, and
  // an undo entry from earlier in this same session does not either.
  state.links = copy(s.links ?? {});
  for (const k of ANSWERS) state[k] = s.answers[k] ?? FRESH[k];
  for (const r of document.querySelectorAll('input[name="bld-theme"]')) r.checked = r.value === state.theme;
  for (const [id, key] of FIELDS) $(`#${id}`).value = state[key];
}

const FIELDS = [['bld-prefix', 'prefix'], ['bld-name', 'name'], ['bld-title', 'title'], ['bld-page', 'page']];

const endRun = () => { run = null; };

// ONE ACTION, ONE ENTRY. Snapshot, run the whole thing, and record only if
// it moved: a move at the end of a slot, a Reset with nothing to reset and a
// field typed back to its original all call a setter and change nothing, and
// none of them is worth an entry the reader would have to press twice.
function change(label, fn) {
  const before = snapshot(), template = state.template;
  fn();
  if (identical(before, snapshot())) return false;
  history = pushed(history, before, label, template);
  endRun();
  syncHistory();
  saveSoon();
  return true;
}

// A keystroke. The FIRST of a run records the state before the run; the rest
// join it. Every boundary that ENDS a run is elsewhere — blur, navigation,
// any change(), undo, redo — because those are events, not values.
function typed(where, label, fn) {
  const key = runKey(state.template, where), now = Date.now();
  const before = snapshot(), template = state.template;
  fn();
  if (identical(before, snapshot())) return;
  if (!sameRun(run, key, now)) history = pushed(history, before, label, template);
  run = { key, at: now };
  syncHistory();
  saveSoon();
}

function step(way) {
  const moved = way === 'undo' ? undone(history, snapshot()) : redone(history, snapshot());
  if (!moved) return;
  history = moved.history;
  endRun();
  applySnapshot(moved.state);
  // Reveal where it happened, in BOTH directions: the entry's template, not
  // the one the reader is standing on and not the snapshot's, either.
  state.template = moved.entry.template;
  $('#bld-template').value = state.template;
  fillSlots();
  fillPicker();
  render();
  syncHistory();
  saveSoon();
}

function syncHistory() {
  const u = $('#bld-undo'), r = $('#bld-redo');
  const last = history.past[history.past.length - 1], next = history.future[history.future.length - 1];
  u.disabled = !last;
  r.disabled = !next;
  u.setAttribute('aria-label', last ? `Undo ${last.label}` : 'Undo');
  r.setAttribute('aria-label', next ? `Redo ${next.label}` : 'Redo');
}

// ── THE DRAFT ──────────────────────────────────────────────────────────────

// Every read and write is wrapped: a private window, a full quota or a store
// the browser has blocked must not break the page.
function writeDraft() {
  if (saveBlocked || unopened) return;
  saveTimer = null;
  try {
    localStorage.setItem(DRAFT_KEY, JSON.stringify(toDraft(snapshot(), id => blocks.get(id)?.html)));
  } catch (e) {
    // NOT THE STATUS LINE. render() rewrites it on every keystroke and would
    // erase this within the second.
    saveBlocked = true;
    alertNotice('Your work is not being saved',
      `The browser refused to store this draft (${e.name || 'error'}), so a reload will lose it. Export the page when you are done.`);
  }
}

const saveSoon = () => {
  if (saveBlocked || unopened) return;
  clearTimeout(saveTimer);
  saveTimer = setTimeout(writeDraft, SAVE_MS);
};

const flushSave = () => { if (saveTimer !== null) { clearTimeout(saveTimer); writeDraft(); } };
const cancelSave = () => { clearTimeout(saveTimer); saveTimer = null; };
const clearDraft = () => { try { localStorage.removeItem(DRAFT_KEY); } catch { /* nothing to do */ } };

// Cloned, never constructed: the two notices are real component markup and
// live in builder.html where check-classes reads them.
//
// TWO REGIONS, AND THAT IS WHY THIS TAKES A BOX. Showing a notice CLEARS its
// container, so routing export feedback through #bld-notice would delete the
// "saved draft was left unopened" warning AND ITS DISCARD BUTTON while
// `unopened` still blocks every save — leaving the reader no way to reach the
// one control that restores saving, and no sign anything was wrong. The same
// applies to the save-failure alert. So #bld-notice is the persistent region,
// owned by the draft and the save, and #bld-export-notice is the transient one
// beside the buttons that caused it. An export never touches the first.
function showNotice(templateId, title, subtitle, action, onAction, into = '#bld-notice') {
  const box = $(into);
  box.textContent = '';
  const node = $(`#${templateId}`).content.cloneNode(true);
  node.querySelector('.rux--actionable-notification__title').textContent = title;
  node.querySelector('.rux--actionable-notification__subtitle').textContent = subtitle;
  const button = node.querySelector('.rux--actionable-notification__action-button');
  if (button) {
    if (action) { button.textContent = action; button.addEventListener('click', onAction); }
    else button.remove();
  }
  box.append(node);
}

const alertNotice = (title, subtitle) => showNotice('bld-alert-template', title, subtitle, null, null);
const exportNotice = (title, subtitle) => showNotice('bld-notice-template', title, subtitle, null, null, '#bld-export-notice');
const exportAlert = (title, subtitle) => showNotice('bld-alert-template', title, subtitle, null, null, '#bld-export-notice');

// On load, before the first render. A draft is opened only when session.mjs
// can establish that it still fits this manifest; anything else is left
// exactly where it is until Discard or Start over explicitly removes it.
function openDraft() {
  let raw = null;
  try { raw = localStorage.getItem(DRAFT_KEY); } catch { return; }
  if (!raw) return;
  const read = fromDraft(raw, manifest);
  if (!read.ok) {
    unopened = true;   // and nothing is saved over it while it sits there
    showNotice('bld-notice-template', 'A saved draft was left unopened',
      `${read.reason}. Nothing has been changed or removed. Discard it to start saving again.`,
      'Discard', () => { unopened = false; clearDraft(); $('#bld-notice').textContent = ''; saveSoon(); });
    return;
  }
  applySnapshot(read.state);
  if (state.pages[state.template] === undefined) {
    const first = Object.keys(read.state.pages)[0];
    if (first) state.template = first;
  }
  showNotice('bld-notice-template', 'Picked up where you left off',
    `This draft was saved ${agoOf(read.savedAt)}. Start over to clear it and begin again.`,
    'Start over', startOver);
}

function startOver() {
  change('start over', () => {
    state.pages = {};
    state.edits = {};
    state.links = {};
    for (const k of ANSWERS) state[k] = FRESH[k];
  });
  applySnapshot(snapshot());          // write the cleared answers into the controls
  // The key goes, and nothing rewrites it until the reader changes something.
  cancelSave();
  clearDraft();
  unopened = false;                 // Start over also discards an incompatible draft
  $('#bld-notice').textContent = '';
  fillSlots();
  fillPicker();
  render();
}

// ── THE PAGE ───────────────────────────────────────────────────────────────

// The composed page and its two readings. `roundTrip` is deliberately
// measured on the template's OWN slot records, unedited and unarranged — that
// check asks whether the builder can reproduce the template it was given,
// and nothing the reader does is supposed to make it fail, so letting the
// model change the answer would destroy the only thing it says. `integrity`
// is the opposite: it reads the page the reader actually built.
async function composed() {
  const src = await source(state.template);
  const t = templateOf(state.template);
  const page = composePage(src, t, pageOf(), manifest, state.edits[state.template] ?? {}, state.links[state.template] ?? {});
  return { page, roundTrip: compose(src, t.slots, blocksOf(t)) === src, integrity: integrity(page) };
}

// `field.raw` is a slice of the original HTML SOURCE, so real text carrying an
// ampersand is stored as the literal bytes `&amp;`. Showing that verbatim in a
// textarea would display the escape sequence itself, and submitting it back
// unchanged would escape it a second time into `&amp;amp;`. One-way and for
// display only: the write path only ever sees plain decoded text.
function decodeText(raw) {
  const probe = document.createElement('textarea');
  probe.innerHTML = raw;
  return probe.value;
}

// The field rows for one entry. `html` MUST be the block's ORIGINAL html from
// the manifest, never an instanced or edited derivative: every recorded index,
// and the original each edit is compared against to decide whether to prune
// it, is an offset into that exact string. Instancing touches no text, so the
// indices hold on the page (proved in stage 4). Saved edits are laid over it
// for display only.
// WHAT A FIELD IS CALLED. Every entry is a class this repository already ships
// and the count it occurs at, taken from the 241 fields in the catalogue rather
// than imagined: the tag alone is useless because div, p and span hold 127 of
// them, and <th> holds none at all — a column header wraps its text in a div.
// The FIRST match down this list wins, so the specific sits above the general.
// Anything unlisted falls back to the tag, which is what the panel said before
// this stage; a wrong name is worse than a plain one.
const ROLES = [
  [/rux--form__helper-text|rux--form-requirement/, 'Helper text'],
  [/rux--checkbox-label-text/, 'Checkbox'],
  [/rux--radio-button__label-text/, 'Radio label'],
  [/rux--toggle__label-text/, 'Toggle label'],
  [/rux--table-header-label/, 'Column header'],
  [/rux--structured-list-th/, 'Column header'],
  [/rux--structured-list-td/, 'Cell'],
  [/rux--tabs__nav-item-label/, 'Tab'],
  [/rux--accordion__title/, 'Section title'],
  [/rux--tag__label/, 'Status'],
  [/rux--inline-notification__title/, 'Notification title'],
  [/rux--inline-notification__subtitle/, 'Notification text'],
  [/rux--list-box__menu-item__option/, 'Option'],
  [/rux--select-option/, 'Option'],
  [/rux--contained-list__label/, 'List label'],
  [/rux--progress-label/, 'Step'],
  [/rux--progress-optional/, 'Step note'],
  [/rux--pagination__/, 'Pagination text'],
  [/rux--full-page-error__label/, 'Error code'],
  [/rux--full-page-error__description/, 'Error text'],
  [/rux--data-table-header__title/, 'Table title'],
  [/rux--data-table-header__description/, 'Table description'],
  [/rux--inline-loading__text/, 'Loading text'],
  [/rux--link/, 'Link'],
  [/rux--btn/, 'Button'],
  [/rux--label/, 'Label'],
  [/rux--list__item/, 'Item'],
];
const BY_TAG = { h1: 'Heading', h2: 'Heading', h3: 'Heading', p: 'Paragraph', td: 'Cell', li: 'Item', a: 'Link', button: 'Button', label: 'Label', legend: 'Legend', option: 'Option' };

// A legend is a <legend class="rux--label">, so it must be read before the
// generic label rule; the tag decides that one, not the class.
function roleOf(f) {
  if (f.name === 'legend') return 'Legend';
  for (const [re, name] of ROLES) if (re.test(f.context.cls)) return name;
  if (BY_TAG[f.name]) return BY_TAG[f.name];
  // AN UNCLASSED WRAPPER TAKES ITS NAME FROM WHAT HOLDS IT. The activity list
  // on dashboard-page is a bare <div> inside li.rux--list__item, and the leaf
  // alone said nothing — it read "Text 21 of 25". The nearest ancestor that
  // has a role does, so ask it before falling back to a position.
  for (const a of [...f.context.chain].reverse()) {
    for (const [re, name] of ROLES) if (re.test(a.cls)) return name;
  }
  return null;
}

// The group a field belongs to, as a stable identity plus a name. `at` is an
// ancestor's content offset, unique inside the block, so two fields under the
// same form item share it by construction rather than by matching text.
const GROUPS = [
  [/rux--form-item/, 'Form item'],
  [/rux--btn-set/, 'Actions'],
  [/rux--table-header-row/, 'Column headers'],
  [/rux--structured-list-row/, 'Row'],
  [/rux--tab-panel/, 'Tab panel'],
  [/rux--contained-list/, 'List'],
  [/rux--accordion__item/, 'Section'],
];
// The NEAREST enclosing unit wins, so the walk is inside out. A fieldset is
// matched by its TAG, not a class: the two in form-page carry
// rux--radio-button-group and rux--checkbox-group and share no class between
// them, and reading it off the class list is what left "Notify me when"
// heading-less on the first run.
function groupOf(f) {
  const inside = [...f.context.chain].reverse();
  // A FIELDSET BEATS ANYTHING NESTED IN IT, and that is not a preference — a
  // fieldset is by definition the set of controls its legend names, so it IS
  // the group. Nearest-unit alone splits one apart: form-page's two checkboxes
  // each sit in their own rux--form-item inside the fieldset while its two
  // radios do not, so "Notify me when" lost its legend to one group and its
  // options to two others, and rendered with no heading at all. Measured on
  // the block, not reasoned about.
  const fs = inside.find(a => a.tag === 'fieldset');
  if (fs) return { at: fs.at, kind: 'Fieldset' };
  for (const a of inside) {
    // The <tr>s carry no class at all, here or in any captured table, so the
    // head is told from the body by its <thead> — without which the first body
    // row read "Row 2", the header row having silently taken Row 1.
    if (a.tag === 'tr') return { at: a.at, kind: inside.some(x => x.tag === 'thead') ? 'Column headers' : 'Row' };
    for (const [re, kind] of GROUPS) if (re.test(a.cls)) return { at: a.at, kind };
  }
  return null;
}

// The field rows for one entry. `html` MUST be the block's ORIGINAL html from
// the manifest, never an instanced or edited derivative: every recorded index,
// and the original each edit is compared against to decide whether to prune
// it, is an offset into that exact string. Instancing touches no text, so the
// indices hold on the page (proved in stage 4). Saved edits are laid over it
// for display only.
function renderFieldPanel(key, html) {
  const box = $('#bld-fields');
  box.textContent = '';
  const fields = textFieldsOf(html);
  const links = linksOf(html);
  if (!fields.length && !links.length) {
    box.append($('#bld-no-fields-template').content.cloneNode(true));
    return;
  }
  const saved = editsFor(state.template, key);
  const savedLinks = linksFor(state.template, key);
  const valueOf = (i, original) => Object.hasOwn(saved, i) ? saved[i] : original;

  // Group first, then name, because a group's heading is one of its own
  // fields: the label or legend inside it. Ungrouped fields keep their order
  // and stand alone, so a block with no form items reads as it did before.
  const groups = new Map();
  const order = [];
  fields.forEach((f, i) => {
    const g = groupOf(f);
    const id = g ? g.at : `solo-${i}`;
    if (!groups.has(id)) { groups.set(id, { g, rows: [] }); order.push(id); }
    groups.get(id).rows.push({ f, i });
  });

  // A FALLBACK NAME IS NUMBERED ONLY WHEN IT HAS TO BE. The first run read
  // "Actions 7" — the seventh div among its siblings, a number that means
  // nothing to a reader. So unnamed groups are numbered by their order among
  // groups of the SAME KIND, and a kind that occurs once stays bare: "Actions",
  // but "Row 1" … "Row 4".
  const kinds = new Map();
  for (const id of order) {
    const g = groups.get(id).g;
    if (g) kinds.set(g.kind, (kinds.get(g.kind) ?? 0) + 1);
  }
  const seen = new Map();
  for (const id of order) {
    const g = groups.get(id).g;
    if (!g) continue;
    const n = (seen.get(g.kind) ?? 0) + 1;
    seen.set(g.kind, n);
    groups.get(id).fallback = kinds.get(g.kind) > 1 ? `${g.kind} ${n}` : g.kind;
  }

  for (const id of order) {
    const { g, rows, fallback } = groups.get(id);
    let rename = null, namingIndex = -1;
    // ONE FIELD, NO HEADING. A heading over a single unlabelled row is chrome
    // for its own sake, and it pushes the eighteen-row panel longer still.
    if (g && rows.length > 1) {
      const head = $('#bld-group-template').content.cloneNode(true);
      const h = head.querySelector('h3');
      // The heading is the group's own label or legend, and it shows the
      // EDITED text: rename Email to Work email and the panel must agree with
      // the preview. An edit may be the empty string — clearing a label is a
      // legal edit — so a blank one falls back to the structural name, and the
      // group's accessible name is never empty.
      // A GROUP IS NAMED BY WHICHEVER OF ITS OWN FIELDS NAMES IT — a legend, a
      // label, or an accordion's title, which is that section's label in all
      // but spelling. Without the last one the detail page's sections read
      // "Section 1" and "Section 2" above rows that already said Environment
      // and Networking.
      const NAMES = new Set(['Legend', 'Label', 'Section title', 'Table title']);
      const naming = rows.find(r => NAMES.has(roleOf(r.f)));
      const named = naming ? valueOf(naming.i, decodeText(naming.f.raw)).trim() : '';
      const wrap = head.querySelector('[role="group"]');
      // LIVE, not only on re-render. The panel is not rebuilt while typing —
      // that would take the caret with it — so the naming row updates its own
      // heading as it goes, or the panel keeps saying Email while the preview
      // says Work email. A blank edit is legal, so the fallback is applied
      // here too and the accessible name is never empty.
      rename = v => {
        h.textContent = (v ?? '').trim() || fallback;
        if (wrap) wrap.setAttribute('aria-label', h.textContent);
      };
      rename(named);
      namingIndex = naming ? naming.i : -1;
      box.append(head);
    }
    for (const { f, i } of rows) {
      const original = decodeText(f.raw);
      const role = roleOf(f);
      const same = rows.filter(r => roleOf(r.f) === role);
      const name = role
        ? (same.length > 1 ? `${role} ${same.findIndex(r => r.i === i) + 1}` : role)
        : `Text ${i + 1} of ${fields.length}`;
      box.append(fieldRow({
        key, i, name,
        hint: role ? null : `In <${f.name}>`,
        original,
        value: valueOf(i, original),
        store: state.edits,
        set: (v) => setEdit(key, i, v, original),
        runKey: `${key}#${i}`,
        label: `edit text in ${labelOf(key)}`,
        rename: i === namingIndex ? rename : null,
      }));
    }
  }

  // Link targets last, and only where there are any: a fragment href is a
  // control relation, not content, and linksOf never offers one.
  links.forEach((l, i) => {
    box.append(fieldRow({
      key, i, name: l.text ? `Link destination — ${l.text}` : 'Link destination',
      hint: null,
      original: decodeText(l.value),
      value: Object.hasOwn(savedLinks, i) ? savedLinks[i] : decodeText(l.value),
      store: state.links,
      set: (v) => setLink(key, i, v, decodeText(l.value)),
      runKey: `${key}$${i}`,          // $ not #, so a link run never joins a text run
      label: `edit a link in ${labelOf(key)}`,
      link: true,
    }));
  });
}

// One row: its name, its value, the original beside it while they differ, and
// a reset that appears only when there is something to reset.
function fieldRow({ key, i, name, hint, original, value, store, set, runKey, label, link, rename }) {
  const row = $('#bld-field-template').content.cloneNode(true);
  const id = `bld-field-${link ? 'link-' : ''}${i}`;
  const el = row.querySelector('label'), area = row.querySelector('textarea');
  el.setAttribute('for', id);
  el.textContent = name;
  area.id = id;
  area.value = value;
  if (link) area.rows = 1;
  const help = row.querySelector('.rux--form__helper-text');
  const reset = row.querySelector('button');
  const sync = () => {
    const edited = Object.hasOwn((store[state.template] ?? {})[key] ?? {}, i);
    // THE ORIGINAL SITS BESIDE THE FIELD while it differs — reset lets someone
    // undo a change, but only this lets them see what they are changing.
    help.textContent = edited ? `original: ${original}` : (hint ?? '');
    help.hidden = !help.textContent;
    reset.hidden = !edited;
  };
  sync();
  area.addEventListener('input', event => {
    // A NATIVE FIELD UNDO IS NOT PART OF THE RUN. The browser owns the
    // undo stack inside a textarea; when it fires one, end our run so the
    // change gets an entry of its own rather than joining the typing it
    // just reversed. The two stacks stay separate, which is stated rather
    // than papered over.
    if (event.inputType && event.inputType.startsWith('history')) endRun();
    typed(runKey, label, () => set(area.value));
    sync();
    if (rename) rename(area.value);
    later();
  });
  area.addEventListener('blur', endRun);
  reset.addEventListener('click', () => {
    change(`reset one field in ${labelOf(key)}`, () => { dropOne(store, key, i); });
    area.value = original;
    sync();
    if (rename) rename(original);
    // The button it was clicked on has just gone; without this, focus falls to
    // the document and the reader loses their place mid-panel.
    area.focus();
    later();
  });
  return row;
}

// Record or prune one override, then keep Reset honest. No history of its
// own: typed() wraps it. One function over both stores, so the pruning rule —
// typing a value back to its original deletes it — cannot drift between them.
function setIn(store, key, i, value, original) {
  const forTemplate = store[state.template] ??= {};
  const forEntry = forTemplate[key] ??= {};
  if (value === original) delete forEntry[i]; else forEntry[i] = value;
  if (!Object.keys(forEntry).length) delete forTemplate[key];
  if (!Object.keys(forTemplate).length) delete store[state.template];
  syncReset();
}
const setEdit = (key, i, value, original) => setIn(state.edits, key, i, value, original);
const setLink = (key, i, value, original) => setIn(state.links, key, i, value, original);

// One field back to its original — the per-field reset. Returns whether it
// changed anything, so change() can record nothing when it did not.
function dropOne(store, key, i) {
  const forTemplate = store[state.template];
  const forEntry = forTemplate?.[key];
  if (!forEntry || !Object.hasOwn(forEntry, i)) return false;
  delete forEntry[i];
  if (!Object.keys(forEntry).length) delete forTemplate[key];
  if (!Object.keys(forTemplate).length) delete store[state.template];
  return true;
}

// REMOVING A BLOCK DROPS BOTH KINDS. Its words and where they pointed go with
// it, or undo brings back a block carrying half its content.
function dropEdits(keys) {
  for (const store of [state.edits, state.links]) {
    const forTemplate = store[state.template];
    if (!forTemplate) continue;
    for (const k of keys) delete forTemplate[k];
    if (!Object.keys(forTemplate).length) delete store[state.template];
  }
}

const countFor = key => Object.keys(editsFor(state.template, key)).length + Object.keys(linksFor(state.template, key)).length;
const syncReset = () => { $('#bld-reset').disabled = !countFor(state.block); };
const editCount = () => [state.edits, state.links]
  .reduce((n, store) => n + Object.values(store[state.template] ?? {}).reduce((m, b) => m + Object.keys(b).length, 0), 0);

const option = (value, text) => {
  const o = document.createElement('option');
  o.className = 'rux--select-option';
  o.value = value; o.textContent = text;
  return o;
};

// The chosen template's slots, and what the chosen one is a container of.
function fillSlots() {
  const t = templateOf(state.template);
  const select = $('#bld-slot');
  select.textContent = '';
  for (const s of t.slots) select.append(option(s.name, s.name));
  state.slot = t.slots.some(s => s.name === state.slot) ? state.slot : t.slots[0].name;
  select.value = state.slot;
  slotNote();
}

function slotNote() {
  const s = templateOf(state.template).slots.find(x => x.name === state.slot);
  const col = s.container?.column ? short(s.container.column) : 'no grid column recorded';
  const stack = s.container?.stack ? short(s.container.stack) : 'no stack — blocks sit flush (composing-pages §3.5)';
  $('#bld-slot-note').textContent = `${col} · ${stack}`;
}

// Every marked block, once, by label and source.
function fillCatalogue() {
  const select = $('#bld-catalogue');
  select.textContent = '';
  for (const b of manifest.blocks) select.append(option(b.id, `${b.label} · ${b.source.replace(/\.html$/, '')}`));
  state.catalogue = manifest.blocks[0].id;
  select.value = state.catalogue;
}

// Fill the block picker from the model, in document order, by label; a
// second instance is numbered, and on a template with several slots the slot
// leads. `keep` is the key to leave selected when it is still on the page.
function fillPicker(keep = state.block) {
  const t = templateOf(state.template);
  const es = entries();
  const select = $('#bld-block');
  select.textContent = '';
  for (const e of es) {
    const b = blocks.get(e.id);
    select.append(option(e.key, `${t.slots.length > 1 ? `${e.slot} · ` : ''}${b.label}${e.n > 1 ? ` (${e.n})` : ''}`));
  }
  state.block = es.some(e => e.key === keep) ? keep : (es[0]?.key ?? '');
  select.value = state.block;
  showBlock();
}

// The panel, the note, the buttons and the preview highlight for whichever
// entry is selected. Nothing about the composed page changed by choosing one,
// so the frame is not reloaded.
function showBlock() {
  const e = entryOf(state.block);
  renderFieldPanel(state.block, e ? blocks.get(e.id).html : '');
  blockNote(e);
  syncButtons(e);
  syncReset();
  highlight();
}

// Where the block was attested, and what it moves with. Information, not a
// rule: the arrangement is the reader's.
function blockNote(e) {
  const note = $('#bld-block-note');
  if (!e) { note.textContent = 'Nothing on the page. Add a block from the catalogue.'; return; }
  const b = blocks.get(e.id);
  const where = b.kind === 'component'
    ? `Attested in the kitchen sink, ${b.source}.`
    : `Attested in ${b.source.replace(/^templates\//, '').replace(/\.html$/, '')}: ${short(b.column) || 'no column'} · ${b.stack ? short(b.stack) : 'no stack'}.`;
  const u = unitOf(pageOf(), e.key);
  const rides = e.follows ? ` Moves and goes with ${labelOf(u.keys[0])}.`
    : u.keys.length > 1 ? ` ${u.keys.slice(1).map(labelOf).join(', ')} moves and goes with it.` : '';
  note.textContent = where + rides;
}

function syncButtons(e) {
  const up = $('#bld-up'), down = $('#bld-down'), rm = $('#bld-remove');
  if (!e) { up.disabled = down.disabled = rm.disabled = true; return; }
  const page = pageOf(), u = unitOf(page, e.key);
  up.disabled = u.start === 0;
  down.disabled = u.end >= page.slots[u.slot].length;
  rm.disabled = false;
}

// Best-effort, and only that: the preview is a document of its own and this
// draws on it. The block's own BLOCK:BEGIN/END comments survive into it, so the
// run of element siblings between them is the block — a run, not one element,
// because a block can have several roots (app-shell's page-title is <h1>+<p>).
// A page may carry the same marker name more than once — a block placed twice,
// or two sources that both call theirs `default` — and the k-th marker in the
// document is the k-th entry with that name in the model, because composePage
// emits slots in template order and entries in model order. Each target's
// existing inline outline is saved and restored rather than blanked, so the
// helper stays non-destructive even though nothing ships one.
let highlighted = [];
function highlight() {
  for (const h of highlighted) { h.el.style.outline = h.outline; h.el.style.outlineOffset = h.offset; }
  highlighted = [];
  const doc = frame.contentDocument;
  const e = entryOf(state.block);
  if (!doc || !doc.body || !e) return;
  const name = blocks.get(e.id).name;
  const k = entries().filter(x => blocks.get(x.id).name === name).findIndex(x => x.key === e.key);
  const walk = doc.createTreeWalker(doc.body, NodeFilter.SHOW_COMMENT);
  let begin = null, seen = 0;
  for (let n; (n = walk.nextNode());) if (n.nodeValue.includes(`BLOCK:BEGIN name=${name} `) && seen++ === k) { begin = n; break; }
  if (!begin) return;
  for (let n = begin.nextSibling; n; n = n.nextSibling) {
    if (n.nodeType === Node.COMMENT_NODE && n.nodeValue.includes(`BLOCK:END ${name}`)) break;
    if (n.nodeType !== Node.ELEMENT_NODE) continue;
    highlighted.push({ el: n, outline: n.style.outline, offset: n.style.outlineOffset });
    n.style.outline = '2px dashed var(--rux-border-interactive)';
    n.style.outlineOffset = '2px';
  }
}

const plural = (n, w) => `${n} ${w}${n === 1 ? '' : 's'}`;

let pending = null;
async function render() {
  const my = pending = {};
  // BEFORE THE TRY, because neither depends on the composition: the command is
  // built from the answers and the template alone, and it must still be right
  // on a page whose preview failed to build.
  $('#bld-command').textContent = command();
  exportWarning();
  try {
    const { page, roundTrip, integrity: ig } = await composed();
    if (pending !== my) return;
    const doc = previewPage(page, answers(), ROOT);
    const url = URL.createObjectURL(new Blob([doc], { type: 'text/html' }));
    frame.addEventListener('load', () => { URL.revokeObjectURL(url); highlighted = []; highlight(); }, { once: true });
    frame.src = url;
    const t = templateOf(state.template);
    const es = entries();
    const natives = t.slots.reduce((n, s) => n + s.blocks.length, 0);
    const kept = es.filter(e => isNative(e, t)).length;
    const arranged = [es.length - kept ? `${es.length - kept} added` : '', natives - kept ? `${natives - kept} removed` : ''].filter(Boolean).join(', ');
    const edits = editCount();
    status.textContent = [
      `${state.template} · ${plural(t.slots.length, 'slot')}, ${plural(es.length, 'block')}${arranged ? ` (${arranged})` : ''}`,
      `round trip ${roundTrip ? 'identical' : 'DIFFERS'}`,
      ig.duplicateIds.length ? `${plural(ig.duplicateIds.length, 'id')} DUPLICATED` : 'ids unique',
      ig.unresolved.length ? `${plural(ig.unresolved.length, 'reference')} unresolved` : 'references resolved',
      state.width === 'fit' ? 'fit to pane' : `${state.width}px`,
      edits ? `${plural(edits, 'field')} edited` : '',
    ].filter(Boolean).join(' · ');
    const named = new Map();
    for (const id of ig.duplicateIds) named.set(`id="${id}" twice or more`, 1);
    for (const r of ig.unresolved) { const k = `${r.attr}="${r.attr === 'href' || r.attr === 'xlink:href' ? '#' : ''}${r.id}"`; named.set(k, (named.get(k) ?? 0) + 1); }
    integrityLine.textContent = named.size ? `On this page: ${[...named].map(([k, n]) => n > 1 ? `${k} ×${n}` : k).join(' · ')}` : '';
    integrityLine.hidden = !named.size;
  } catch (e) {
    status.textContent = `Could not build the preview: ${e.message}`;
  }
}

function setWidth(w) {
  state.width = w;
  for (const b of document.querySelectorAll('[data-width]')) b.setAttribute('aria-pressed', String(b.dataset.width === w));
  if (w === 'fit') {
    frame.style.inlineSize = '100%';
    wrap.style.transform = '';
    wrap.style.blockSize = '';
    wrap.style.inlineSize = '';
  } else {
    const px = Number(w);
    const pane = wrap.parentElement.clientWidth;
    const scale = Math.min(1, pane / px);
    frame.style.inlineSize = `${px}px`;
    wrap.style.inlineSize = `${px}px`;
    wrap.style.transform = scale < 1 ? `scale(${scale})` : '';
    wrap.style.blockSize = scale < 1 ? `${frame.getBoundingClientRect().height * scale}px` : '';
  }
  render();
}

let timer;
const later = () => { clearTimeout(timer); timer = setTimeout(render, 250); };

// The three arrangements. Each is one transaction: the pure transition, the
// edits that go with it, and nothing else.
function addBlock() {
  const label = blocks.get(state.catalogue)?.label ?? 'block';
  let placed = null;
  change(`add ${label}`, () => {
    setPage(add(pageOf(), state.slot, state.catalogue, manifest));
    const list = pageOf().slots[state.slot];
    placed = unitOf(pageOf(), list[list.length - 1].key).keys[0];
  });
  fillPicker(placed ?? state.block);
  render();
}

function moveBlock(dir) {
  if (!state.block) return;
  const label = labelOf(state.block), key = state.block;
  change(`move ${label} ${dir < 0 ? 'up' : 'down'}`, () => setPage(move(pageOf(), key, dir)));
  fillPicker(key);
  render();
}

function removeBlock() {
  if (!state.block) return;
  const es = entries();
  const u = unitOf(pageOf(), state.block);
  const at = es.findIndex(e => e.key === u.keys[0]);
  const label = labelOf(u.keys[0]);
  // ONE ENTRY, THOUGH IT TOUCHES TWO THINGS. The block's text goes with the
  // block; undo brings both back together or the reader has lost their words
  // to a button that said Remove.
  change(`remove ${label}`, () => {
    dropEdits(u.keys);
    setPage(remove(pageOf(), state.block));
  });
  const rest = entries();
  fillPicker(rest[Math.min(at, rest.length - 1)]?.key ?? '');
  render();
}

// ── taking it away ─────────────────────────────────────────────────────────
//
// ONE DEFINITION OF THE FILE NAME, used by the download and by the command,
// because the two would otherwise disagree in a way nobody sees until the
// script dies. `page` is a FILE NAME, never a path: new-project.sh writes
// `> "$DIR/$PAGE.html"` and creates no parent directory, so `reports/orders`
// kills it under `set -e`, while a browser's download attribute quietly
// flattens the separator and writes the file anyway. A trailing `.html` is
// stripped rather than rejected — the field says "without .html", and typing
// it is the obvious slip, not an error worth a lecture.
function normalisePage() {
  const raw = state.page.trim().replace(/\.html$/i, '');
  if (!raw || /[/\\]/.test(raw)) return { name: 'index', why: raw ? `“${raw}” has a path separator; the script writes one file beside the project's own index.html` : '' };
  return { name: raw, why: '' };
}

// Every answer single-quoted, so nothing in it is read by the shell. The
// FOLDER IS DELIBERATELY ABSENT: supplying every other flag leaves the script
// asking exactly one question, first, with its own default. The builder does
// not know the reader's folders, and a placeholder path they might run without
// reading is the trap this avoids.
const sq = s => `'${String(s).split("'").join("'\\''")}'`;
function command() {
  const a = answers();
  return ['./tools/new-project.sh',
    '--template', sq(state.template), '--theme', sq(a.theme),
    '--prefix', sq(a.prefix), '--name', sq(a.name),
    '--title', sq(a.title), '--page', sq(normalisePage().name)].join(' ');
}

// NEITHER SIDE ESCAPES HTML, and check-parity says so in its own words: an
// answer carrying " < > or & lands unescaped in element text and in an
// aria-label, so it can make markup both sides agree on byte for byte and no
// browser reads as intended. The builder will not escape unilaterally — that
// would break the parity contract it just earned — so it says so instead.
// Whether to escape in both, reject in both, or leave it is rux's: §4.12.
function exportWarning() {
  const a = answers();
  const bad = [['product prefix', a.prefix], ['product name', a.name], ['browser tab title', a.title]]
    .map(([label, v]) => [label, [...new Set((v.match(/["<>&]/g) ?? []))].join(' ')])
    .filter(([, chars]) => chars);
  const line = $('#bld-export-warn');
  const page = normalisePage();
  const notes = [
    bad.length ? `${bad.map(([l, c]) => `the ${l} carries ${c}`).join(', ')} — neither the export nor new-project.sh escapes these, so the page may not read as you intend.` : '',
    page.why,
  ].filter(Boolean);
  line.textContent = notes.join(' ');
  line.hidden = !notes.length;
}

async function downloadPage() {
  try {
    const doc = exportPage((await composed()).page, answers());
    const url = URL.createObjectURL(new Blob([doc], { type: 'text/html' }));
    // An unclassed anchor, the way decodeText() makes an unclassed textarea:
    // this file invents no rux-- markup, and neither of these is any.
    const a = document.createElement('a');
    a.href = url;
    a.download = `${normalisePage().name}.html`;
    a.click();
    // NOT REVOKED ON THE NEXT LINE. The preview's URL is revoked on the
    // iframe's `load`, because there the consumer announces it has the bytes;
    // a download announces nothing, and revoking in the same tick as the click
    // has been observed to abort the save. So it is released on a timer — long
    // enough that the browser has taken it, short enough that a session of
    // exports does not accumulate documents in memory.
    setTimeout(() => URL.revokeObjectURL(url), 10_000);
    exportNotice('Downloaded', `${a.download} — put it beside the project's own index.html. Its paths already point at vendor/rux-ds/.`);
  } catch (e) {
    exportAlert('Could not build the page', e.message);
  }
}

async function copyText(what, text, subtitle) {
  try {
    await navigator.clipboard.writeText(text);
    exportNotice(`${what} copied`, subtitle);
  } catch (e) {
    // The same call js/copy-button.js makes, and the same reason it does not
    // go silent: a copy that failed and said nothing is worse than one that
    // says where to look.
    exportAlert(`Could not copy the ${what.toLowerCase()}`, `${e.message}. It is on window.RuxBuilder if you need it from the console.`);
  }
}

async function init() {
  try {
    manifest = JSON.parse(await fetchText('builder/blocks.json'));
  } catch (e) {
    status.textContent = `Could not load builder/blocks.json: ${e.message}. Serve this repository (node tools/serve.mjs) rather than opening the file.`;
    return;
  }
  for (const b of manifest.blocks) blocks.set(b.id, b);
  const select = $('#bld-template');
  for (const t of manifest.templates) select.append(option(t.name, t.name));

  openDraft();                       // before the first render, after the manifest

  select.value = state.template;
  select.addEventListener('change', () => { endRun(); state.template = select.value; fillSlots(); fillPicker(); render(); });
  const slot = $('#bld-slot');
  slot.addEventListener('change', () => { endRun(); state.slot = slot.value; slotNote(); });
  const catalogue = $('#bld-catalogue');
  catalogue.addEventListener('change', () => { endRun(); state.catalogue = catalogue.value; });
  $('#bld-add').addEventListener('click', addBlock);
  $('#bld-up').addEventListener('click', () => moveBlock(-1));
  $('#bld-down').addEventListener('click', () => moveBlock(+1));
  $('#bld-remove').addEventListener('click', removeBlock);
  $('#bld-undo').addEventListener('click', () => step('undo'));
  $('#bld-redo').addEventListener('click', () => step('redo'));
  $('#bld-start-over').addEventListener('click', startOver);
  $('#bld-download').addEventListener('click', downloadPage);
  $('#bld-copy').addEventListener('click', async () => {
    try {
      const main = bodyOnly(exportPage((await composed()).page, answers()));
      if (!main) return exportAlert('Nothing to copy', 'this page has no <main> region.');
      await copyText('Main region', main, 'It is the whole <main> element, so it REPLACES the main region of the page you paste it into.');
    } catch (e) { exportAlert('Could not build the page', e.message); }
  });
  $('#bld-copy-command').addEventListener('click', () =>
    copyText('Command', command(), 'Run it from your rux-ds clone; it will ask where to put the project.'));
  const picker = $('#bld-block');
  picker.addEventListener('change', () => { endRun(); state.block = picker.value; showBlock(); });
  $('#bld-reset').addEventListener('click', () => {
    const key = state.block;
    change(`reset ${labelOf(key)}`, () => dropEdits([key]));
    showBlock();
    later();
  });
  for (const r of document.querySelectorAll('input[name="bld-theme"]')) {
    r.addEventListener('change', () => {
      if (!r.checked) return;
      change(`theme ${r.nextElementSibling?.textContent.trim() || r.value}`, () => { state.theme = r.value; });
      render();
    });
  }
  for (const [id, key] of FIELDS) {
    const input = $(`#${id}`);
    input.addEventListener('input', event => {
      if (event.inputType && event.inputType.startsWith('history')) endRun();
      typed(id, `${key === 'page' ? 'file name' : key}`, () => { state[key] = input.value; });
      later();
    });
    input.addEventListener('blur', endRun);
  }
  for (const b of document.querySelectorAll('[data-width]')) b.addEventListener('click', () => setWidth(b.dataset.width));
  window.addEventListener('resize', () => { if (state.width !== 'fit') setWidth(state.width); });

  // The field's own undo owns the field. Everywhere else, ours does.
  document.addEventListener('keydown', event => {
    if (!(event.metaKey || event.ctrlKey) || event.key.toLowerCase() !== 'z') return;
    const t = event.target;
    if (t && (t.tagName === 'TEXTAREA' || (t.tagName === 'INPUT' && t.type === 'text'))) return;
    event.preventDefault();
    step(event.shiftKey ? 'redo' : 'undo');
  });
  // A debounce is a promise to write in half a second, which a reload does
  // not wait for. Both events, because neither fires reliably alone.
  window.addEventListener('pagehide', flushSave);
  document.addEventListener('visibilitychange', () => { if (document.visibilityState === 'hidden') flushSave(); });

  fillCatalogue();
  fillSlots();
  fillPicker();
  syncHistory();
  render();
}

// For the console and the gates' operator: the page the export would write,
// the model, the history, and every action driven without the buttons.
window.RuxBuilder = {
  state,
  page: async () => exportPage((await composed()).page, answers()),
  main: async () => bodyOnly(exportPage((await composed()).page, answers())),
  command,
  fileName: normalisePage,
  download: downloadPage,
  roundTrip: async () => (await composed()).roundTrip,
  integrity: async () => (await composed()).integrity,
  model: () => pageOf(),
  history: () => ({ past: history.past.map(e => e.label), future: history.future.map(e => e.label) }),
  run: () => (run ? { key: run.key, age: Date.now() - run.at } : null),
  add: (slot, id) => { state.slot = slot; state.catalogue = id; addBlock(); },
  move: (key, dir) => { state.block = key; moveBlock(dir); },
  remove: key => { state.block = key; removeBlock(); },
  undo: () => step('undo'),
  redo: () => step('redo'),
  startOver,
  flushSave,
  // Exposed so the no-fields branch — which no shipped block triggers — can be
  // driven through the real clone-into-DOM path rather than left untested.
  renderFieldPanel,
};

init();
