#!/usr/bin/env node
//
// Writes builder.html — the page builder, creator 3 (roadmap §4.12). Generated
// and committed like kitchen-sink.html and portal.html, for the same reason:
// everything on it derives from files on disk, and a hand-maintained copy
// would drift. `npm run builder`; regenerated by `npm run verify`.
//
// WHAT THE PAGE IS. A template picker, the four answers tools/new-project.sh
// asks (theme, prefix, name, title) plus the page file name, and a live
// preview of the page those choices produce — in an iframe, because the
// composed page has its own header and rendering it inline here would show
// two shells, which is exactly what roadmap §4.12's "no frames" line forbids.
// The catalogue of blocks, editing and export come in later stages; this page
// is the skeleton round trip first, because a builder that cannot reproduce an
// unedited template byte for byte has no business editing one.
//
// NO SPRITE MARKERS. tools/lib/sources.mjs spritePages() hands any root page
// carrying SPRITE:BEGIN to `npm run icons` as a writer; this file is already
// that page's writer, and two writers on one region is the drift the markers
// exist to stop. assets/icons.svg is inlined here directly, and every glyph
// the page uses is asserted against it — the build-portal-icons pattern —
// because a <use> at a missing symbol paints nothing, silently.
//
// THE CHROME IS bld-. Layout the builder itself needs — the preview box, the
// width row — is an inline <style> on --rux-* tokens with bld- classes, which
// check-classes ignores exactly as it ignores the sink's ks-, and which
// check-tokens reads because this is a root page. The component markup is
// the sink's own (select, radio group, text input, buttons) and the shell is
// portal.html's, header-only.
//
// THE PREVIEW IS OUTSIDE EVERY GATE. check-a11y and the rest query the top
// document and do not descend into an iframe; sweeping this page measures the
// builder's chrome, not the page inside it. The page says so.
import { readFileSync, writeFileSync } from 'node:fs';

const sprite = readFileSync('assets/icons.svg', 'utf8').trim();
const symbols = new Set([...sprite.matchAll(/<symbol\s+id="([^"]+)"/g)].map(m => m[1]));

const THEMES = [['white', 'White'], ['g10', 'Gray 10'], ['g90', 'Gray 90'], ['g100', 'Gray 100'], ['rux', 'Rux']];
const WIDTHS = [['375', '375'], ['672', '672'], ['1056', '1056'], ['1280', '1280'], ['1440', '1440'], ['fit', 'Fit']];

const textInput = (id, label, placeholder, helper) => `
          <div class="rux--form-item rux--text-input-wrapper">
            <div class="rux--text-input__label-wrapper">
              <label class="rux--label" for="${id}">${label}</label>
            </div>
            <div class="rux--text-input__field-outer-wrapper">
              <div class="rux--text-input__field-wrapper">
                <input id="${id}" class="rux--text-input" type="text" placeholder="${placeholder}">
              </div>
            </div>
            <div class="rux--form__helper-text">${helper}</div>
          </div>`;

const page = `<!doctype html>
<html lang="en" data-theme="white">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>rux-ds — builder</title>
<link rel="preload" as="font" type="font/woff2" crossorigin href="assets/fonts/IBMPlexSans-Regular-Latin1.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin href="assets/fonts/IBMPlexSans-SemiBold-Latin1.woff2">
<link rel="stylesheet" href="assets/fonts/plex.css">
<link rel="stylesheet" href="css/rux.css">
<link rel="stylesheet" href="css/rux-theme.css">
<link rel="stylesheet" href="css/rux-overrides.css">
<script src="js/theme.js"></script>
<style>
/* The builder's own layout, bld- so check-classes ignores it the way it
   ignores the sink's ks-. Tokens only; no colour or size is invented. */
.bld-preview { background: var(--rux-layer-01); border: 1px solid var(--rux-border-subtle-01); padding: var(--rux-spacing-05); overflow: auto; }
.bld-frame-wrap { transform-origin: top left; }
.bld-frame { display: block; inline-size: 100%; block-size: 48rem; border: 0; background: var(--rux-background); }
.bld-widths { display: flex; flex-wrap: wrap; gap: var(--rux-spacing-03); }
.bld-status { color: var(--rux-text-secondary); }
</style>
</head>
<body>
<!-- GENERATED by tools/build-builder.mjs — do not edit. Edit the generator. -->
<!-- PROVENANCE: rendered-dom · the shell is portal.html's, header-only, from
     components-ui-shell-header--header-w-navigation-actions-and-side-nav
     captured 2026-08-31; the controls are sink/select.html, sink/radio.html,
     sink/text-input.html and sink/buttons.html markup, verbatim -->
<!-- BEHAVIOUR: derived · builder/builder.js is rux's own, not Carbon's: it
     composes a template from builder/blocks.json and previews it. What the
     gates measure on this page is its chrome. NOT COVERED, by construction:
     anything inside the preview iframe — check-a11y, check-spacing and
     check-runtime-classes read the top document only. The exported page is
     the thing to sweep, and nothing here will do that once it leaves. -->

${sprite}

<header class="rux--header" data-theme="g100" aria-label="rux-ds">
  <a class="rux--skip-to-content" href="#main-content">Skip to main content</a>
  <a class="rux--header__name" href="builder.html"><span class="rux--header__name--prefix">Rux</span>&nbsp;DS</a>
  <nav class="rux--header__nav" aria-label="rux-ds">
    <ul class="rux--header__menu-bar">
      <li><a class="rux--header__menu-item" href="portal.html"><span class="rux--text-truncate-end">Portal</span></a></li>
      <li><a class="rux--header__menu-item" href="kitchen-sink.html"><span class="rux--text-truncate-end">Kitchen sink</span></a></li>
      <li><a class="rux--header__menu-item rux--header__menu-item--current" href="builder.html" aria-current="page"><span class="rux--text-truncate-end">Builder</span></a></li>
    </ul>
  </nav>
</header>

<main id="main-content" class="rux--content">
  <div class="rux--css-grid">
    <div class="rux--css-grid-column rux--col-span-100">
      <div class="rux--stack-vertical rux--stack-scale-7">
        <div class="rux--stack-vertical rux--stack-scale-5">
          <h1>Page builder</h1>
          <p>Start from a template and see the page it makes. The preview is the real page in a frame of its own; what it cannot promise is the composition — every part is attested, the arrangement is yours, and <code>docs/composing-pages.md</code> §3.10 says what that means.</p>
        </div>
        <div class="rux--subgrid rux--subgrid--wide rux--subgrid--with-row-gap">

          <div class="rux--css-grid-column rux--sm:col-span-4 rux--md:col-span-8 rux--lg:col-span-5">
            <div class="rux--stack-vertical rux--stack-scale-7">
              <h2>Choices</h2>
              <div class="rux--form-item">
                <div class="rux--select">
                  <label class="rux--label" for="bld-template">Template</label>
                  <div class="rux--select-input__wrapper">
                    <select id="bld-template" class="rux--select-input"></select>
                    <svg class="rux--select__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--down"/></svg>
                  </div>
                  <div class="rux--form__helper-text">One of the ten in <code>templates/</code>, as <code>new-project.sh</code> offers them.</div>
                </div>
              </div>
              <div class="rux--form-item">
                <fieldset class="rux--radio-button-group rux--radio-button-group--label-right rux--radio-button-group--vertical" id="bld-theme">
                  <legend class="rux--label">Default theme</legend>
${THEMES.map(([v, l]) => `                  <div class="rux--radio-button-wrapper">
                    <input id="bld-theme-${v}" class="rux--radio-button" type="radio" name="bld-theme" value="${v}"${v === 'white' ? ' checked' : ''}>
                    <label for="bld-theme-${v}" class="rux--radio-button__label">
                      <span class="rux--radio-button__appearance"></span>
                      <span class="rux--radio-button__label-text">${l}</span>
                    </label>
                  </div>`).join('\n')}
                </fieldset>
                <div class="rux--form__helper-text">The page's default. A visitor's own choice, saved in the account panel, wins on the real page; the preview shows the default.</div>
              </div>${textInput('bld-prefix', 'Product prefix', 'Rux', 'The lighter-weight half of the header name.')}${textInput('bld-name', 'Product name', 'DS', 'The header name and its aria-label.')}${textInput('bld-title', 'Browser tab title', 'Prefix and name', 'Defaults to the prefix and the name, as the script does.')}${textInput('bld-page', 'File name', 'index', 'Without .html — what the export downloads as.')}
            </div>
          </div>

          <div class="rux--css-grid-column rux--sm:col-span-4 rux--md:col-span-8 rux--lg:col-span-11">
            <div class="rux--stack-vertical rux--stack-scale-5">
              <h2>Preview</h2>
              <div class="bld-widths" role="group" aria-label="Preview width">
${WIDTHS.map(([v, l]) => `                <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" data-width="${v}" aria-pressed="${v === 'fit'}">${l}</button>`).join('\n')}
              </div>
              <p class="bld-status" id="bld-status">Loading the catalogue…</p>
              <div class="bld-preview">
                <div class="bld-frame-wrap" id="bld-frame-wrap">
                  <iframe class="bld-frame" id="bld-frame" title="Preview of the composed page"></iframe>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</main>

<script src="js/overlay.js"></script>
<script src="js/popover.js"></script>
<script src="js/menu.js"></script>
<script src="js/list-box.js"></script>
<script src="js/tabs.js"></script>
<script src="js/accordion.js"></script>
<script src="js/data-table.js"></script>
<script src="js/form-controls.js"></script>
<script src="js/ui-shell.js"></script>
<script src="js/dismiss.js"></script>
<script src="js/tile.js"></script>
<script src="js/modal.js"></script>
<script type="module" src="builder/builder.js"></script>
</body>
</html>
`;

// Every glyph this page references must exist in the sprite it inlines.
const body = page.slice(page.indexOf('</svg>') + 6);
const missing = [...new Set([...body.matchAll(/<use\s+href="#(i-[^"]+)"/g)].map(m => m[1]))].filter(id => !symbols.has(id));
if (missing.length) {
  for (const id of missing) console.log(`  build-builder: no <symbol id="${id}"> in assets/icons.svg`);
  process.exit(1);
}
writeFileSync('builder.html', page);
console.log(`  builder.html — ${(page.length / 1024).toFixed(0)} KB · ${symbols.size} symbols inlined`);
